spring:
  datasource:
    url: jdbc:mysql://localhost:3306/file_system_db
    username: root
    password: 'Prabodham@36'

jwt:
  secret: "Qk1vQ2J4b3J2b2d6d2p3b2ZyQ2J4b3J2b2d6d2p3b2ZyQk1vQ2J4b3J2b2d6d2p3b2ZyQk1vQ2J4b3J2b2d6d2p3b2ZyQk1vQ2J4b3I="
  expiration-ms: 86400000
